//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Usuarios
    {
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Edad { get; set; }
        public string CURP { get; set; }
        public string Genero { get; set; }
        public string Rol { get; set; }
        public int Id { get; set; }
        public string Contrasena { get; set; }
        public string estado { get; set; }
    }
}
